### ISSUE TITLE
Mach port support

### ISSUE THREAD

**Issue by bugaevc** [stjepang/async-io#15]
I would like to watch Mach ports for new messages using smol.

There are basically two ways to go about watching a Mach port. One, which would work on any Mach system, is to have the reactor use Mach port sets in place of current epoll/kqueue.

Another way, which only works on Darwin, is to use `EVFILT_MACHPORT` with kqueue. This could then be exposed in `Async` with a `cfg` (e.g. `Async::mach_port(...)`).

**Comment by stjepang** [comment]
This issue sort of fell off my radar and I forgot about it. Then a lot of things happened and now the raw I/O stuff is in the `polling` crate. :)

Right now, my feeling is that attempting to shoehorn mach port support into `polling`/`async-io` is going to be difficult and am doubting whether that is even worth it.

Instead, what I would probably prefer to do (at least initially) is to put mach port support separately into a new crate that creates its own reactor and spawns a thread handling I/O events. If we can do that successfully and present an ergonomic API, it will be easier to see how to merge it into the `async-io` design (if we'll still want to do that).

**Comment by bugaevc** [comment]
In that case, it might make sense to wrap libdispatch with futures-based Rust API instead of wrapping raw Mach (or kqueue) API. There's a trade-off between high performance and being most native to the underlying platform.

**Comment by stjepang** [comment]
Just leaving a link to this PR with mach port implementation for future reference: https://github.com/stjepang/async-io/issues/15#issuecomment-682585540

**Comment by stjepang** [comment]
Closing since it's unlikely `async-io` will gain mach port support in the near future.
