### ISSUE TITLE
Linker error in stable-x86_64-pc-windows-gnu toolchain

### ISSUE THREAD

**Issue by Nonakesh** [stjepang/async-io#16]
Since async-std switched to smol I'm unable to compile my project in the stable-gnu toolchain. It's working perfectly in stable-msvc as well as native linux compilation.

I'm getting the following error:
```error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1``` 

And multiple missing functions like this:
``` In function `smol::reactor::sys::Reactor::new::h4fc4018e596093ae':```
```...\src\github.com-1ecc6299db9ec823\smol-0.1.18\src/reactor.rs:741: undefined reference to `epoll_create1'```

For the functions `epoll_create1`, `epoll_ctl`, and `epoll_wait`.

I'm using the default compiler that comes with installing the toolchain with rustup. Maybe I'm missing a library?

**Comment by stjepang** [comment]
I have just updated wepoll and am able to cross-compile with gnu toolchain. Can someone verify if this issue is now resolved?

**Comment by stjepang** [comment]
Okay, looks like it works in CI so this seems to be resolved now! :)

https://github.com/stjepang/async-io/runs/1113276441
