### ISSUE TITLE
Async::<UnixStream>::connect returning with io::ErrorKind::WouldBlock

### ISSUE THREAD

**Issue by JayceFayne** [stjepang/async-io#18]
I am in the process of moving [swayipc](https://github.com/JayceFayne/swayipc-rs/tree/next) from `async-std` to `async-io`. While running the unit tests I encountered tests failing with `io::ErrorKind::WouldBlock`. After re-running the current tests with the latest version of `async-std` I encountered the same behaviour (since `async-std` moved to `async-io`). The unit tests run without failing on `async-std` version 1.5 since this is the last version using `mio-uds`. I extracted an example on how to reproduce this bug:
```rust
use async_io::Async;
use futures_lite::future;
use std::os::unix::net::UnixStream;
use std::thread;

fn main() {
    let mut handles = Vec::new();
    for _ in 1..100 {
        let handle = thread::spawn(|| {
            future::block_on(async {
                Async::<UnixStream>::connect("pathtosomeunixsocket").await
            })
        });
        handles.push(handle);
    }
    for handle in handles {
        if let Err(error) = handle.join().unwrap() {
            dbg!(error);
        }
    }
}
```

**Comment by stjepang** [comment]
Thanks for the report! Can you see if this fixes the bug? https://github.com/stjepang/async-io/pull/19

**Comment by JayceFayne** [comment]
I tried to debug and fix this bug as well since yesterday and came up with the same solution you propose in #19. Unfortunately this does not fix the problem. Calling `connect` does not error out with `io::ErrorKind::WouldBlock` anymore but therefore a write to the socket results in `io::ErrorKind::NotConnected`. I believe that `stream.writable().await?` [here](https://github.com/stjepang/async-io/blob/master/src/lib.rs#L1192) does not wait until the socket is connected

**Comment by stjepang** [comment]
Hmmm. I wonder what happens if you await `writable()` twice?

```rust
stream.writable().await?;
stream.writable().await?;
```

If this resolves the issue, then indeed there is a problem in `writable()`.

**Comment by JayceFayne** [comment]
> Hmmm. I wonder what happens if you await `writable()` twice?
I tried it out but it did not change anything as far as I can tell. With #19 applied a write to the socket still sometimes fails with `io::ErrorKind::NotConnected`. The behaviour is pretty inconsistent. It does not happen on every connect/write but rather if there are multiple threads trying to establish a connection (e.g. in unit tests). 
> Do you perhaps have a reproducible example for the issue that remains even after #19 is applied?
I created a repo with an reproducible example [here](https://github.com/JayceFayne/async-io-unixstream-error). It uses the swayipc socket, I have not tested it with other sockets yet.

**Comment by stjepang** [comment]
Ok I was able to reproduce. The error eventually pops up even if I do this:

```rust
fn main() -> std::io::Result<()> {
    use futures_lite::io::AsyncWriteExt;
    future::block_on(async {
        for step in 0..500_000 {
            dbg!(step);
            let mut conn =
                Async::<UnixStream>::connect("/run/user/1000/sway-ipc.1000.1358.sock")
                .await?;
            conn.write(&[]).await?;
        }
        Ok(())
    })
}
```

Error:

```
[src/main.rs:11] step = 10703
Error: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }
```

The same happens with tokio:

```rust
#[tokio::main]
async fn main() -> std::io::Result<()> {
    use tokio::prelude::*;
    for step in 0..500_000 {
        dbg!(step);
        let mut conn =
            tokio::net::UnixStream::connect("/run/user/1000/sway-ipc.1000.1358.sock")
            .await?;
        conn.write(&[]).await?;
    }
    Ok(())
}
```

Perhaps swaywm is just dropping connections occasionally? Maybe if it gets slammed with too many connections at once, it can't keep up so it has to drop some of them?

**Comment by stjepang** [comment]
I also tried adding a sleep after the `write()` fails - it seems that the connection is never (re)established, which makes me believe that it is not `writable()` at fault. The connection is simply broken.

**Comment by JayceFayne** [comment]
> Ok I was able to reproduce. The error eventually pops up even if I do this:

Hmm. Interesting, does not seem related to threads after all..

> Perhaps swaywm is just dropping connections occasionally? Maybe if it gets slammed with too many connections at once, it can't keep up so it has to drop some of them?

It seem to me pretty unlikely that sway is dropping connections since the unit tests for the swayipc library are just 26 tests. At the moment some of them fail with and without #19. Furthermore establishing connections to sways IPC socket with async-std version 1.5 [works](https://github.com/JayceFayne/async-io-unixstream-error/tree/async-std-1-5) without any errors. I also wrote a blocking version of that test [here](https://github.com/JayceFayne/async-io-unixstream-error/tree/blocking) and everything went fine until something overflowed (40k threads/connections) :smile:

**Comment by JayceFayne** [comment]
> I also tried adding a sleep after the `write()` fails - it seems that the connection is never (re)established, which makes me believe that it is not `writable()` at fault. The socket is not in the "connecting" state". Rather, the connection is simply broken.

Since it is kinda hard to debug this issue by relying on sways IPC I rewrote the example I posted earlier to be ["self contained"](https://github.com/JayceFayne/async-io-unixstream-error). The test can be run by passing a flag e.g. `RUST_LOG=async_io_unixstream_error=trace cargo r -- async-io`. `blocking` and `async-std` behave (the same and) like expected and do not return `io::ErrorKind::NotConnected` while `async-io` does. I hope this helps fixing the `io::ErrorKind::NotConnected` error.

**Comment by stjepang** [comment]
Ah I see. So async-std v1.5.0 creates a `UnixStream` connection in a blocking way (using `spawn_blocking()`) and then creates an async `UnixStream` handle from a connected sync `UnixStream` handle.

I believe that when the socket is in blocking mode and the OS exhausts its internal resources, the `UnixStream::connect()` call will just block until it can connect. And in non-blocking mode connecting fails right away. That's my theory at least, and failing immediately is probably the right thing to do here :)

I was able to reproduce this behavior on my linux VM, but not on macOS. On macOS I get the `NotConnected` error in all cases.

**Comment by JayceFayne** [comment]
> Ah I see. So async-std v1.5.0 creates a `UnixStream` connection in a blocking way (using `spawn_blocking()`) and then creates an async `UnixStream` handle from a connected sync `UnixStream` handle.

Yep

> I believe that when the socket is in blocking mode and the OS exhausts its internal resources, the `UnixStream::connect()` call will just block until it can connect. And in non-blocking mode connecting fails right away. That's my theory at least, and failing immediately is probably the right thing to do here :)

Currently calling `Async::<UnixStream>::connect` does not fail immediately. It rather fails with `NotConnected` on the next write call. I was able to fail fast by adding [this line](https://github.com/JayceFayne/async-io/commit/8100926fbcd601578ce2b2e86f03aba2e7fd3e27) to the connect function. With this patch applied I was also able to fix the example posted earlier by [connecting in a loop](https://github.com/JayceFayne/async-io-unixstream-error/commit/994e414632c2ace56c1a57c6f6f8e7a2e1aa95c9). Not sure if that's the best way to do this but...it works :smile: 

> I was able to reproduce this behavior on my linux VM, but not on macOS. On macOS I get the `NotConnected` error in all cases.

I tested all above mentioned changes on linux.

**Comment by stjepang** [comment]
Hmmm, that's interesting! Could you perhaps do me a favor and try one more thing?

Instead of using `stream.get_ref().peer_addr()`, try `stream.get_ref().take_error()` like so:

```rust
        // The stream becomes writable when connected.
        stream.writable().await?;

        // Check if there was an error while connecting.
        match stream.get_ref().take_error()? {
            None => Ok(stream),
            Some(err) => Err(err),
        }
```

That should be the cleanest solution.

In fact, if you look at how `Async::<TcpStream>::connect()` is implemented, it contains this exact same `take_error()` check at the end. But, I believed this is not necessary when connecting with a `UnixStream` because `mio` doesn't do it and I couldn't find any indication that this is necessary in the man pages. But it may be!

**Comment by JayceFayne** [comment]
> Hmmm, that's interesting! Could you perhaps do me a favor and try one more thing?
> 
> Instead of using `stream.get_ref().peer_addr()`, try `stream.get_ref().take_error()` like so:
> 
> ```rust
>         // The stream becomes writable when connected.
>         stream.writable().await?;
> 
>         // Check if there was an error while connecting.
>         match stream.get_ref().take_error()? {
>             None => Ok(stream),
>             Some(err) => Err(err),
>         }
> ```
> 
> That should be the cleanest solution.

Yes I thought so as well but while testing yesterday I noticed that at least on linux (might be different on macOS?) `take_error` does not return an error. I saw that the `peer` field on the debugging output of `UnixStream` [was missing](https://doc.rust-lang.org/nightly/src/std/sys/unix/ext/net.rs.html#279-291). That's why I ended up using `peer_addr` instead of `take_error`. I also tried to add a timeout like you did to see if the socket eventually reaches a connected state (basically by checking `peer_addr` in a loop) but for some reason it always errors out with `NotConnected` :/

**Comment by stjepang** [comment]
That's really odd - could be just a quirk in the Linux implementation of Unix domain sockets. :/ But, I would be fine with adding this workaround using `peer_addr()` anyways. It seems like we need it.

**Comment by JayceFayne** [comment]
> That's really odd - could be just a quirk in the Linux implementation of Unix domain sockets. :/ 

Maybe...idk. You mentioned that you have a macOS system? I would be really interested if it behaves the same way :smile: 
> But, I would be fine with adding this workaround using peer_addr() anyways. It seems like we need it.

Alright, I will close this issue for now since #19 fixed the initial bug anyway.
Thanks for your help!

I opened #21 regarding the the `peer_addr` workaround ;)

**Comment by stjepang** [comment]
On macOS, `connect()` blows up right away:

```
[2020-08-28T13:15:50Z TRACE async_io_unixstream_error::test] send msg #129
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 61, kind: ConnectionRefused, message: "Connection refused" }', src/test/async_io.rs:10:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
